### ISSUE TITLE
Could you please give me a more detailed guide?

### ISSUE THREAD

**Issue by Tossy654** [bdamitz/todoistgcalsync#9]
It looks great from the demo video. But I'm not familiar with python. Could you please write a more detailed README file? Thx!🙂

**Comment by bdamitz** [comment]
This project is now deprecated before it ever really began. haha Todoist just introduced a 2-way sync integration. So the best guide I can give is:
1. Go to Todoist Settings
2. Go to Integrations
3. Click on "Connect" for Google Calendar
[https://blog.todoist.com/2017/05/17/google-calendar-todoist-integration/](https://blog.todoist.com/2017/05/17/google-calendar-todoist-integration/)
